# Generated by Django 6.1 on 2026-08-11 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('format', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('location', models.CharField(blank=True, help_text='Required for offline events, must be null for online events.', max_length=255, null=True)),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('reconfirmation_required', 'Reconfirmation required')], max_length=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
