# Generated by Django 6.1 on 2026-08-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='reconfirmation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
