"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import sys
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.User'


# Application definition

INSTALLED_APPS = [
    'apps.users',
    'apps.events',
    'apps.notifications',
    'apps.webui',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'django_crontab',
    'django_rq',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB'),
        'USER': env('POSTGRES_USER'),
        'PASSWORD': env('POSTGRES_PASSWORD'),
        'HOST': env('POSTGRES_HOST', default='localhost'),
        'PORT': env('POSTGRES_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email (docs/email-integration-spec.md §4)
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# Dev: SMTP to Mailpit (docker-compose service) for a real, clickable inbox.
# Tests: Django's test runner overrides TestCase's mailer to locmem
# automatically regardless of this setting, so `mail.outbox` works without
# Mailpit being up.

MAILERS = {
    'default': {
        'BACKEND': env('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend'),
        'OPTIONS': {
            'host': env('EMAIL_HOST', default='mailpit'),
            'port': env.int('EMAIL_PORT', default=1025),
            'use_tls': env.bool('EMAIL_USE_TLS', default=False),
            'username': env('EMAIL_HOST_USER', default=''),
            'password': env('EMAIL_HOST_PASSWORD', default=''),
        },
    },
}
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@example.com')


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.users.authentication.CookieJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
        'apps.users.permissions.CookieCSRFPermission',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # TODO: point this at a custom handler that renders the ADR-002
    # {"error": {"code", "message"}} shape for domain/business exceptions,
    # while leaving DRF's default field-error shape for validation errors.
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Rates differ per endpoint (ADR 003 "rate limiting on auth endpoints"),
    # so throttle_classes are attached per-view rather than globally; the
    # rates themselves are still declared centrally here.
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/min',
        'login-ip': '20/min',
        'password-reset': '5/min',
        'password-reset-ip': '20/min',
        'email-verification': '5/min',
        'email-verification-ip': '20/min',
        'refresh': '30/min',
        'register': '10/hour',
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Event Manager API',
    'DESCRIPTION': 'API per ADRs.',
    'VERSION': 'v1',
    'SERVE_INCLUDE_SCHEMA': False,
    # Strip the version prefix before auto-deriving tags, so Swagger groups
    # endpoints by logical part (auth / users / events) instead of by
    # everything falling under one "v1" bucket.
    'SCHEMA_PATH_PREFIX': r'/api/v1',
}

# django-rest-framework-simplejwt
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html
#
# Tokens are issued as usual but delivered to the client via HttpOnly cookies
# (see apps/users/authentication.py and apps/users/views.py) rather than in
# the response body. Refresh-token rotation is enabled; reuse detection /
# token-family revocation is business logic left as a TODO (needs a
# supporting model that does not exist yet).

from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    # Reuse detection (apps/users/models.py: RefreshTokenFamily/Record) now
    # rejects a rotated-out token before simplejwt's own blacklist is even
    # consulted, so this is safe to enable as a defense-in-depth check.
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    # Dedicated signing key, separate from Django's SECRET_KEY (ADR 003:
    # rotating SECRET_KEY for unrelated reasons must not invalidate every
    # live JWT, and compromising one must not compromise the other).
    'SIGNING_KEY': env('JWT_SIGNING_KEY'),
    'ALGORITHM': 'HS256',  # pinned per RFC 8725 §3.1, never left implicit
}

AUTH_COOKIE_ACCESS_NAME = 'access_token'
AUTH_COOKIE_REFRESH_NAME = 'refresh_token'
AUTH_COOKIE_SECURE = not DEBUG
AUTH_COOKIE_HTTPONLY = True
AUTH_COOKIE_SAMESITE = 'Lax'
# The refresh cookie is only ever needed on the auth endpoints that consume
# it (refresh, logout) — scoping its path shrinks the surface that could
# leak this long-lived, high-value token (ADR 003).
AUTH_COOKIE_REFRESH_PATH = '/api/v1/auth/'

# Readable-by-JS double-submit CSRF cookie, paired with an X-CSRF-Token
# header on cookie-authenticated state-changing requests (ADR 003 CSRF
# defense-in-depth; see apps/users/permissions.py::CookieCSRFPermission).
AUTH_CSRF_COOKIE_NAME = 'csrf_token'

# apps/users/management/commands/cleanup_expired_tokens.py — prunes expired
# RefreshTokenRecord/Family rows (ADR 003). Requires `manage.py crontab add`
# to be run once per deployment to register this with system cron.
CRONJOBS = [
    ('0 * * * *', 'django.core.management.call_command', ['cleanup_expired_tokens']),
    ('*/15 * * * *', 'django.core.management.call_command', ['expire_reconfirmations']),
]


# Task queue (docs/email-integration-spec.md §5) — RQ, not Celery: the only
# async need is send-email-after-commit plus §6's future periodic TTL job,
# which doesn't justify Celery's broker tuning/beat scheduler/Flower.
# `worker` (docker-compose) runs `manage.py rqworker default` against this
# same queue. ASYNC=False lets tests run jobs inline against a real Redis
# without a separate worker process.
_running_tests = 'test' in sys.argv
_redis_url = env('REDIS_URL', default='redis://redis:6379/0')
if _running_tests:
    # Redirect to a separate Redis DB (15, never listened to by `worker`)
    # instead of whatever DB REDIS_URL points at — otherwise, when a test
    # deliberately leaves a job ASYNC/queued (e.g. to inspect its retry
    # policy), the real `worker` process racing against the same Redis
    # instance can dequeue and run it before the assertion runs.
    _redis_url = _redis_url.rsplit('/', 1)[0] + '/15'

RQ_QUEUES = {
    'default': {
        'URL': _redis_url,
        'DEFAULT_TIMEOUT': 360,
        # default False under `manage.py test` (see comment above) so jobs
        # run inline instead of sitting unconsumed in Redis; overridable
        # via RQ_ASYNC either way.
        'ASYNC': env.bool('RQ_ASYNC', default=not _running_tests),
    },
}
